<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>Media Center</title>
	</head>
	<body>
		<h1>Weah!</h1>
		
		<form method="post" enctype="multipart/form-data" action="http://mediacenter.dev/upload">
             <h1>Ajouter un media</h1>
             <p>
             	<input name="file" id="file" type="file" />
             </p>
             <p>
             	<input type="submit" name="submit" />
             </p>
        </form>
		
		<form method="post" enctype="multipart/form-data" action="http://mediacenter.dev/curl_upload">
             <h1>Ajouter un media (cURL)</h1>
             <p>
             	<input name="file" id="file" type="file" />
             </p>
             <p>
             	<input type="submit" name="submit" />
             </p>
        </form>
	</body>
</html>